object e4Main extends App {
	println("calcolo il 5° numero di fibonacci:")
	println(e4.fibo(5))
	println("calcolo il 10° numero di fibonacci:")
	println(e4.fibo(10))
	println("calcolo il 20° numero di fibonacci:")
	println(e4.fibo(20))
	println("uso fibo2")
	println("calcolo il 18° numero di fibonacci:")
	println(e4.fibo2(18))
	println("calcolo il 19° numero di fibonacci:")
	println(e4.fibo2(19))
	println("uso fibo3")
	println("calcolo il 21° numero di fibonacci:")
	println(e4.fibo3(21))
	println("calcolo il 46° (massimo rappresentabile) numero di fibonacci:")
	println(e4.fibo3(46))
}
